[[<%= namespace %>]]
type = "text"
title = "Send Logs to AWS S3"
description = """\
Now that we have Vector up and running, let's send the logs to S3.\
"""

[[<%= namespace %>.steps]]
type = "text"
title = "Ensure Vector has write permission to your S3 bucket"
description = """\
Depending on how you're deploying Vector, you'll want to make sure Vector \
has write access to your AWS S3 bucket. Setting up AWS permissions is covered \
in a separate guide. Fortunately, Vector implements healthchecks, and will \
verify access before starting.\
"""

[[<%= namespace %>.steps]]
type = "text"
title = "Add the `aws_s3` sink to your `vector.toml` file"
description = """\
```bash
echo '...' > vector.toml
```

Now start Vector like you did previously:

```bash
start_vector
```

Tada! You've successfully sent $source logs to S3.
"""
